employee/Employe/urls.py
from django.contrib import admin
from django.urls import path
from Employe import views
app_name="empl"

urlpatterns = [
    path('',views.home,name='home'),
    path('view',views.viewemployess,name='view'),
    path('add',views.addemployee,name='add'),
    path('edit/<int:n>/',views.editemployee,name="edit"),
    path('delete/<int:n>/',views.delete,name="del"),
    path('details/<int:n>/',views.details,name='details'),
    path('reg',views.register,name="register"),
    path('log',views.user_login,name="login"),
]

employee/employee/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Employe.urls'))
]

employee/Employe/models.py
from django.db import models

# Create your models here.
class employess(models.Model):
    name=models.CharField(max_length=20)
    department=models.CharField(max_length=30)
    id=models.IntegerField(primary_key=True)
    age=models.IntegerField()

    def __str__(self):
        return self.name

employee/Employe/forms.py
from django import forms
from Employe.models import employess


class Employeeform(forms.ModelForm):
    class Meta:
        model=employess
        fields='__all__'

employee/Employe/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect

from Employe.models import employess

from Employe.forms import Employeeform


# Create your views here.
def viewemployess(request):
    e = employess.objects.all()
    return render(request,'view.html',{'emp':e})

def home(request):
    return render(request,'home.html')

def addemployee(request):
    if (request.method=="POST"):
        i = request.POST['i']
        n = request.POST['n']
        d= request.POST['d']
        a= request.POST['a']
        e= employess.objects.create(id=i,name=n,department=d,age=a)
        e.save()
        return home(request)
    return render(request,'add.html')


def editemployee(request,n):
    e=employess.objects.get(id=n)
    if(request.method=="POST"):
        form=Employeeform(request.POST,request.FILES,instance=e)
        if form.is_valid():
            form.save()
            return home(request)
    form=Employeeform(instance=e)
    return render(request,'edit.html',{'form':form})


def delete(request,n):
    e=employess.objects.get(id=n)
    e.delete()
    return home(request)
def register(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        cp=request.POST['cp']
        e=request.POST['e']
        f=request.POST['f']
        l=request.POST['l']

        if(cp==p):
            user=User.objects.create_user(username=u,password=p,email=e,first_name=f,last_name=l)
            user.save()
            return redirect('empl:home')
        else:
            return HttpResponse("passwords are not same")
    return render(request,'register.html')



def user_login(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        user=authenticate(username=u,password=p)
        if user:
            login(request,user)
            return redirect('empl:home')
        else:
            return HttpResponse("invalid credentials")
    return render(request,'login.html')


def details(request,n):
    e=employess.objects.get(id=n)
    return render(request,'details.html',{'emp':e})

employee/templates/add.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<h2 class="text-center">Add Employess</h2>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

<div class="mb-3">
  <label class="form-label">ID</label>
    <input type="number" class="form-control" name="i" placeholder="enter id">
</div>
<div class="mb-3">
  <label class="form-label">Name</label>
  <input type="text" class="form-control"  name="n"  placeholder="enter name">
</div>
<div class="mb-3">
  <label class="form-label">Department</label>
    <input type="text" class="form-control" name="d" placeholder="enter department name">
</div>

<div class="mb-3">
  <label class="form-label">age</label>
    <input type="number" class="form-control" name="a" placeholder="enter the age">
</div>
    <div class="mb-3">
  <button type="submit" class="btn btn-primary">Submit</button>

</div>


</form></center>
{% endblock %}

employee/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body style="background-color:grey"><nav class="navbar navbar-expand-lg navbar-light bg-secondary">
<!--  <div class="container-fluid">-->
<!--    <a class="navbar-brand" href="#">Navbar</a>-->
<!--    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">-->
<!--      <span class="navbar-toggler-icon"></span>-->
<!--    </button>-->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active"  href="{% url 'empl:home' %}">Home</a>

        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'empl:view' %}">View</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'empl:add' %}">Add Employee</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'empl:register' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'empl:login' %}">Login</a>
        </li>
<!--        <li class="nav-item dropdown">-->
<!--          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">-->
<!--            Dropdown-->
<!--          </a>-->
<!--          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--            <li><a class="dropdown-item" href="#">Action</a></li>-->
<!--            <li><a class="dropdown-item" href="#">Another action</a></li>-->
<!--            <li><hr class="dropdown-divider"></li>-->
<!--            <li><a class="dropdown-item" href="#">Something else here</a></li>-->
<!--          </ul>-->
<!--        </li>-->

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}


</body>
</html>

employee/templates/details.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h3>Employee Details</h3>
<table class="table table-bordered border-secondary">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Department</th>
        <th>Age</th>
        <th>Edit</th>
    </tr>

    <tr>
        <td>{{emp.id}}</td>
        <td>{{emp.name}}</td>
        <td>{{emp.department}}</td>
        <td>{{emp.age}}</td>

        <td><a href="{% url 'empl:edit' emp.id %}" class="btn btn-success">Edit</a></td>


    </tr>



{% endblock %}
    </table>

employee/templates/edit.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block content %}
<center>

  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
<!--      <table>-->
<!--          {{form.as_table}}</table>-->
      <button type="submit">SUBMIT</button>
  </form>
    {% endblock %}

employee/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block title %}
Home
{% endblock %}


{% block content %}
<h2 class="text-center">Welcome to Home Page.....!!</h2>
{% endblock %}

employee/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}
Login
{% endblock %}
{% block content %}
<h2 class="text-center">LOGIN</h2>


     <form method="POST">
         {% csrf_token %}




<div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control"  name="u" placeholder="enter username">
</div>
<div class="mb-3">
  <label class="form-label">Password</label>
    <input type="password" class="form-control" name="p" placeholder="enter password">
</div>
<div class="mb-3">
    <button type="submit" class="btn btn-primary">SUBMIT</button>

{% endblock %}

employee/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Register
{% endblock %}
{% block content %}
<h2 class="text-center">REGISTER HERE.....</h2>

     <form method="POST">
       {% csrf_token %}

<div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control"  name="u" placeholder="enter username">
</div>
<div class="mb-3">
  <label class="form-label">Password</label>
    <input type="password" class="form-control" name="p" placeholder="enter password">
</div>
<div class="mb-3">
  <label class="form-label">Confirm Password</label>
    <input type="password" class="form-control" name="cp" placeholder="enter confirm password">
</div>
<div class="mb-3">
  <label class="form-label">Email</label>
    <input type="text" class="form-control" name="e" placeholder="enter email">
</div>
    <div class="mb-3">
  <label class="form-label">First name</label>
    <input type="text" class="form-control" name="f" placeholder="enter firstname">
        <div class="mb-3">
  <label class="form-label">Last name</label>
    <input type="text" class="form-control" name="l" placeholder="enter lastname">

</div>
<div class="mb-3">
  <button type="submit" class="btn btn-dark">Submit</button>
{% endblock %}

employee/templates/view.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block title %}
Home
{% endblock %}


{% block content %}

<h3>Employee Details</h3>
<table class="table table-bordered border-secondary">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Department</th>
        <th>Age</th>
        <th>Details</th>
<!--       <th>Edit</th>-->

        <th>Delete</th>
    </tr>
    {% for i in emp %}
    <tr>
        <td>{{i.id}}</td>
        <td>{{i.name}}</td>
        <td>{{i.department}}</td>
        <td>{{i.age}}</td>

      <td><a href="{% url 'empl:details' i.id %}" class="btn btn-dark">Details</a></td>

        <td><a href="{% url 'empl:del' i.id %}" class="btn btn-dark">Delete</a></td>

    </tr>

    {% endfor %}
</table>
{% endblock %}